name: Execução de Testes
on:
    workflow_call:

jobs:
    unit-test:
        name: Teste de Unidade
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o codigo do projeto
              uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "8.0.300"
            - name: Execução do teste de unidade
              working-directory: ./src
              run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj

    integration-test:
        name: Teste de integração
        runs-on: ubuntu-latest
        services:
            postgre:
                image: postgres:latest
                ports:
                    - 5432:5432
                env: 
                    POSTGRES_USER: review
                    POSTGRES_PASSWORD: postgrespwd
                    POSTGRES_DB: review-filmes
        steps:
            - name: Obtendo o codigo do projeto
              uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "8.0.300"
            - name: Execução do teste de integracao
              working-directory: ./src
              run: dotnet test ./Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj
              env:
                ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=review-filmes;Username=review;Password=postgrespwd"

    # sonarqube:
    #     name: Scan com sonarqube
    #     runs-on: [self-hosted]
    #     steps:
    #         - name: Obtendo o codigo do projeto
    #           uses: actions/checkout@v4
    #         - name: Setup JDK
    #           uses: actions/setup-java@v4
    #           with:
    #                 java-version: '21'
    #                 distribution: temurin
    #         - name: Force env .NET para path
    #           run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
    #         - name: Setup dotnet
    #           uses: actions/setup-dotnet@v4
    #           with:
    #               dotnet-version: "8.0.300"
    #         #   env:
    #         #     DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet
    #         - name: Instalação sonarqube scan
    #           run: dotnet tool install --global dotnet-sonarscanner
    #         - name: Build e analise
    #           working-directory: ./src
    #           run: |
    #                 dotnet sonarscanner begin /k:"filmes" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"  /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
    #                 dotnet build Review-Filmes.sln
    #                 dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    sonarqube:
        name: Scan com sonarqube
        runs-on: self-hosted

        container:
            image: mcr.microsoft.com/dotnet/sdk:8.0

        steps:
            - name: Obtendo o codigo do projeto
              uses: actions/checkout@v4

            - name: Instalar Java
              run: |
                apt-get update
            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                    java-version: '21'
                    distribution: temurin

            - name: Instalar SonarScanner
              run: dotnet tool install --global dotnet-sonarscanner

            - name: Adicionar tools ao PATH
              run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

            - name: Build e analise
              working-directory: ./src
              run: |
                dotnet sonarscanner begin /k:"filmes" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"  /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
                dotnet build Review-Filmes.sln
                dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

            - name: SonarQube Quality Gate check
              uses: sonarsource/sonarqube-quality-gate-action@master
              id: sonarqube-quality-gate-check
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              with:
                scanMetadataReportFile: ./src/.sonarqube/.sonar/report-task.txt
            - name: Show Quality Gate Status
              if: ${{ always() }}
              run: echo "Status do quality gate eh ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status}}"
                
